### ISSUE TITLE
Fix Sensu CPU check

### ISSUE THREAD

**Issue by flamingspaz** [mozilla/parsys#150]
Invalid check argument(s): invalid option: -p, ["/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/mixlib-cli-1.7.0/lib/mixlib/cli.rb:230:in `parse_options'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.4.2/lib/sensu-plugin/cli.rb:13:in `initialize'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.4.2/lib/sensu-plugin/cli.rb:57:in `new'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.4.2/lib/sensu-plugin/cli.rb:57:in `block in <class:CLI>'"]

**Comment by flamingspaz** [comment]
`-p` (Average load across all cores) isn't a valid option anymore, opened https://github.com/mozilla/partinfra-playbooks/pull/140 to remove it.

**Comment by flamingspaz** [comment]
`CheckLoad OK: Per core load average (2 CPU): [0.01, 0.03, 0.03]`
